//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.28 at 08:33:38 PM CET 
//


package nl.tt_solutions.schemas.ns.rti._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.tt_solutions.schemas.ns.rti._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.tt_solutions.schemas.ns.rti._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlatformInfoType }
     * 
     */
    public PlatformInfoType createPlatformInfoType() {
        return new PlatformInfoType();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceType }
     * 
     */
    public ServiceInfoServiceType createServiceInfoServiceType() {
        return new ServiceInfoServiceType();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceJitType }
     * 
     */
    public ServiceInfoServiceJitType createServiceInfoServiceJitType() {
        return new ServiceInfoServiceJitType();
    }

    /**
     * Create an instance of {@link ServiceInputJitType }
     * 
     */
    public ServiceInputJitType createServiceInputJitType() {
        return new ServiceInputJitType();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceJitList }
     * 
     */
    public ServiceInfoServiceJitList createServiceInfoServiceJitList() {
        return new ServiceInfoServiceJitList();
    }

    /**
     * Create an instance of {@link PlatformInfoStopType }
     * 
     */
    public PlatformInfoStopType createPlatformInfoStopType() {
        return new PlatformInfoStopType();
    }

    /**
     * Create an instance of {@link RtiMonitorInputType }
     * 
     */
    public RtiMonitorInputType createRtiMonitorInputType() {
        return new RtiMonitorInputType();
    }

    /**
     * Create an instance of {@link PlatFormInfoList }
     * 
     */
    public PlatFormInfoList createPlatFormInfoList() {
        return new PlatFormInfoList();
    }

    /**
     * Create an instance of {@link PlatformInfoReturn }
     * 
     */
    public PlatformInfoReturn createPlatformInfoReturn() {
        return new PlatformInfoReturn();
    }

    /**
     * Create an instance of {@link ServiceInputType }
     * 
     */
    public ServiceInputType createServiceInputType() {
        return new ServiceInputType();
    }

    /**
     * Create an instance of {@link ServiceInfoReturn }
     * 
     */
    public ServiceInfoReturn createServiceInfoReturn() {
        return new ServiceInfoReturn();
    }

    /**
     * Create an instance of {@link ServiceInfoStopType }
     * 
     */
    public ServiceInfoStopType createServiceInfoStopType() {
        return new ServiceInfoStopType();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceList }
     * 
     */
    public ServiceInfoServiceList createServiceInfoServiceList() {
        return new ServiceInfoServiceList();
    }

    /**
     * Create an instance of {@link PlatformInfoType.StopList }
     * 
     */
    public PlatformInfoType.StopList createPlatformInfoTypeStopList() {
        return new PlatformInfoType.StopList();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceType.StopList }
     * 
     */
    public ServiceInfoServiceType.StopList createServiceInfoServiceTypeStopList() {
        return new ServiceInfoServiceType.StopList();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceJitType.StopList }
     * 
     */
    public ServiceInfoServiceJitType.StopList createServiceInfoServiceJitTypeStopList() {
        return new ServiceInfoServiceJitType.StopList();
    }

}
