//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.28 at 08:33:38 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/")
package nl.tt_solutions.schemas.ns.rti._1;
