//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Het actuele overzicht van alle vertrekkende ritten die binnen een bepaalde tijdshorizon vertrekken van een bepaald station.
 * 
 * <p>Java class for ActueleVertrekTijdenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActueleVertrekTijdenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VertrekStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *         &lt;element name="VertrekInformatie" type="{urn:ndov:cdm:trein:reisinformatie:data:2}VertrekInformatieType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Versie" type="{urn:ndov:cdm:trein:reisinformatie:data:2}Versietype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActueleVertrekTijdenType", propOrder = {
    "vertrekStation",
    "vertrekInformatie"
})
public class ActueleVertrekTijdenType {

    @XmlElement(name = "VertrekStation", required = true)
    protected StationType vertrekStation;
    @XmlElement(name = "VertrekInformatie", required = true)
    protected List<VertrekInformatieType> vertrekInformatie;
    @XmlAttribute(name = "Versie")
    protected String versie;

    /**
     * Gets the value of the vertrekStation property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getVertrekStation() {
        return vertrekStation;
    }

    /**
     * Sets the value of the vertrekStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setVertrekStation(StationType value) {
        this.vertrekStation = value;
    }

    /**
     * Gets the value of the vertrekInformatie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vertrekInformatie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVertrekInformatie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.VertrekInformatieType }
     * 
     * 
     */
    public List<VertrekInformatieType> getVertrekInformatie() {
        if (vertrekInformatie == null) {
            vertrekInformatie = new ArrayList<VertrekInformatieType>();
        }
        return this.vertrekInformatie;
    }

    /**
     * Gets the value of the versie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersie() {
        return versie;
    }

    /**
     * Sets the value of the versie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersie(String value) {
        this.versie = value;
    }

}
