//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * Het element DynamischeVertrekStaat bevat de geplande en actuele gegevens van één vertrekkende trein op één station op één bepaalde geldigheidsdatum.
 * 
 * <p>Java class for DynamischeVertrekStaatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DynamischeVertrekStaatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RitId" type="{urn:ndov:cdm:trein:reisinformatie:data:2}RitIdType"/>
 *         &lt;element name="RitDatum" type="{urn:ndov:cdm:trein:reisinformatie:data:2}RitDatumType"/>
 *         &lt;element name="RitStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *         &lt;element name="VerstoringOnderweg" type="{urn:ndov:cdm:trein:reisinformatie:data:2}VerstoringOnderwegType" minOccurs="0"/>
 *         &lt;element name="Trein" type="{urn:ndov:cdm:trein:reisinformatie:data:2}TreinType"/>
 *         &lt;element name="PresentatieOpmerkingen" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamischeVertrekStaatType", propOrder = {
    "ritId",
    "ritDatum",
    "ritStation",
    "verstoringOnderweg",
    "trein",
    "presentatieOpmerkingen",
    "any"
})
public class DynamischeVertrekStaatType {

    @XmlElement(name = "RitId", required = true)
    protected BigInteger ritId;
    @XmlElement(name = "RitDatum", required = true)
    protected XMLGregorianCalendar ritDatum;
    @XmlElement(name = "RitStation", required = true)
    protected StationType ritStation;
    @XmlElement(name = "VerstoringOnderweg")
    protected VerstoringOnderwegType verstoringOnderweg;
    @XmlElement(name = "Trein", required = true)
    protected TreinType trein;
    @XmlElement(name = "PresentatieOpmerkingen")
    protected MeertaligeUitingenType presentatieOpmerkingen;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the ritId property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getRitId() {
        return ritId;
    }

    /**
     * Sets the value of the ritId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setRitId(BigInteger value) {
        this.ritId = value;
    }

    /**
     * Gets the value of the ritDatum property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRitDatum() {
        return ritDatum;
    }

    /**
     * Sets the value of the ritDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setRitDatum(XMLGregorianCalendar value) {
        this.ritDatum = value;
    }

    /**
     * Gets the value of the ritStation property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getRitStation() {
        return ritStation;
    }

    /**
     * Sets the value of the ritStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setRitStation(StationType value) {
        this.ritStation = value;
    }

    /**
     * Gets the value of the verstoringOnderweg property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.VerstoringOnderwegType }
     *     
     */
    public VerstoringOnderwegType getVerstoringOnderweg() {
        return verstoringOnderweg;
    }

    /**
     * Sets the value of the verstoringOnderweg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.VerstoringOnderwegType }
     *     
     */
    public void setVerstoringOnderweg(VerstoringOnderwegType value) {
        this.verstoringOnderweg = value;
    }

    /**
     * Gets the value of the trein property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.TreinType }
     *     
     */
    public TreinType getTrein() {
        return trein;
    }

    /**
     * Sets the value of the trein property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.TreinType }
     *     
     */
    public void setTrein(TreinType value) {
        this.trein = value;
    }

    /**
     * Gets the value of the presentatieOpmerkingen property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieOpmerkingen() {
        return presentatieOpmerkingen;
    }

    /**
     * Sets the value of the presentatieOpmerkingen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.MeertaligeUitingenType }
     *     
     */
    public void setPresentatieOpmerkingen(MeertaligeUitingenType value) {
        this.presentatieOpmerkingen = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3c.dom.Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }
}
