//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dit element bevat een actueel overzicht van alle vertrekkende ritten die binnen een bepaalde tijdshorizon vertrekken van een bepaald station.
 * 
 * <p>Java class for GeefActueleVertrekTijdenResponseMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeefActueleVertrekTijdenResponseMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BerichtStatus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GeefActueleVertrekTijdenRequestMessage" type="{urn:ndov:cdm:trein:reisinformatie:data:2}GeefActueleVertrekTijdenRequestMessageType"/>
 *         &lt;element name="ActueleVertrekTijden" type="{urn:ndov:cdm:trein:reisinformatie:data:2}ActueleVertrekTijdenType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeefActueleVertrekTijdenResponseMessageType", propOrder = {
    "berichtStatus",
    "geefActueleVertrekTijdenRequestMessage",
    "actueleVertrekTijden"
})
public class GeefActueleVertrekTijdenResponseMessageType {

    @XmlElement(name = "BerichtStatus")
    protected int berichtStatus;
    @XmlElement(name = "GeefActueleVertrekTijdenRequestMessage", required = true)
    protected GeefActueleVertrekTijdenRequestMessageType geefActueleVertrekTijdenRequestMessage;
    @XmlElement(name = "ActueleVertrekTijden")
    protected ActueleVertrekTijdenType actueleVertrekTijden;
    @XmlAttribute(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;

    /**
     * Gets the value of the berichtStatus property.
     * 
     */
    public int getBerichtStatus() {
        return berichtStatus;
    }

    /**
     * Sets the value of the berichtStatus property.
     * 
     */
    public void setBerichtStatus(int value) {
        this.berichtStatus = value;
    }

    /**
     * Gets the value of the geefActueleVertrekTijdenRequestMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.GeefActueleVertrekTijdenRequestMessageType }
     *     
     */
    public GeefActueleVertrekTijdenRequestMessageType getGeefActueleVertrekTijdenRequestMessage() {
        return geefActueleVertrekTijdenRequestMessage;
    }

    /**
     * Sets the value of the geefActueleVertrekTijdenRequestMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.GeefActueleVertrekTijdenRequestMessageType }
     *     
     */
    public void setGeefActueleVertrekTijdenRequestMessage(GeefActueleVertrekTijdenRequestMessageType value) {
        this.geefActueleVertrekTijdenRequestMessage = value;
    }

    /**
     * Gets the value of the actueleVertrekTijden property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.ActueleVertrekTijdenType }
     *     
     */
    public ActueleVertrekTijdenType getActueleVertrekTijden() {
        return actueleVertrekTijden;
    }

    /**
     * Sets the value of the actueleVertrekTijden property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.ActueleVertrekTijdenType }
     *     
     */
    public void setActueleVertrekTijden(ActueleVertrekTijdenType value) {
        this.actueleVertrekTijden = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

}
