//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * De vraag voor actuele vertrektijden
 * 
 * <p>Java class for GeefActueleVertrekTijdenRequestMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeefActueleVertrekTijdenRequestMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StationCode" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationCodeType"/>
 *         &lt;element name="MinimumResultaten" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="MaximumResultaten" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="HorizonStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="HorizonEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TaalCodes" type="{urn:ndov:cdm:trein:reisinformatie:data:2}TaalCodesType" minOccurs="0"/>
 *         &lt;element name="Aanvrager" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeefActueleVertrekTijdenRequestMessageType", propOrder = {
    "stationCode",
    "minimumResultaten",
    "maximumResultaten",
    "horizonStart",
    "horizonEnd",
    "taalCodes",
    "aanvrager"
})
public class GeefActueleVertrekTijdenRequestMessageType {

    @XmlElement(name = "StationCode", required = true)
    protected String stationCode;
    @XmlElement(name = "MinimumResultaten")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minimumResultaten;
    @XmlElement(name = "MaximumResultaten")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maximumResultaten;
    @XmlElement(name = "HorizonStart")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar horizonStart;
    @XmlElement(name = "HorizonEnd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar horizonEnd;
    @XmlElement(name = "TaalCodes")
    protected TaalCodesType taalCodes;
    @XmlElement(name = "Aanvrager", required = true)
    protected String aanvrager;
    @XmlAttribute(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;

    /**
     * Gets the value of the stationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * Sets the value of the stationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationCode(String value) {
        this.stationCode = value;
    }

    /**
     * Gets the value of the minimumResultaten property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMinimumResultaten() {
        return minimumResultaten;
    }

    /**
     * Sets the value of the minimumResultaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMinimumResultaten(BigInteger value) {
        this.minimumResultaten = value;
    }

    /**
     * Gets the value of the maximumResultaten property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMaximumResultaten() {
        return maximumResultaten;
    }

    /**
     * Sets the value of the maximumResultaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMaximumResultaten(BigInteger value) {
        this.maximumResultaten = value;
    }

    /**
     * Gets the value of the horizonStart property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHorizonStart() {
        return horizonStart;
    }

    /**
     * Sets the value of the horizonStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setHorizonStart(XMLGregorianCalendar value) {
        this.horizonStart = value;
    }

    /**
     * Gets the value of the horizonEnd property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHorizonEnd() {
        return horizonEnd;
    }

    /**
     * Sets the value of the horizonEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setHorizonEnd(XMLGregorianCalendar value) {
        this.horizonEnd = value;
    }

    /**
     * Gets the value of the taalCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.TaalCodesType }
     *     
     */
    public TaalCodesType getTaalCodes() {
        return taalCodes;
    }

    /**
     * Sets the value of the taalCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.TaalCodesType }
     *     
     */
    public void setTaalCodes(TaalCodesType value) {
        this.taalCodes = value;
    }

    /**
     * Gets the value of the aanvrager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAanvrager() {
        return aanvrager;
    }

    /**
     * Sets the value of the aanvrager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAanvrager(String value) {
        this.aanvrager = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

}
