//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GeefActueleVertrekTijdenFaultMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeefActueleVertrekTijdenFaultMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Foutnummer" type="{urn:ndov:cdm:trein:reisinformatie:data:2}FoutnummerType"/>
 *         &lt;element name="Omschrijving" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GeefActueleVertrekTijdenRequestMessage" type="{urn:ndov:cdm:trein:reisinformatie:data:2}GeefActueleVertrekTijdenRequestMessageType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeefActueleVertrekTijdenFaultMessageType", propOrder = {
    "foutnummer",
    "omschrijving",
    "geefActueleVertrekTijdenRequestMessage"
})
public class GeefActueleVertrekTijdenFaultMessageType {

    @XmlElement(name = "Foutnummer")
    protected int foutnummer;
    @XmlElement(name = "Omschrijving", required = true)
    protected String omschrijving;
    @XmlElement(name = "GeefActueleVertrekTijdenRequestMessage", required = true)
    protected GeefActueleVertrekTijdenRequestMessageType geefActueleVertrekTijdenRequestMessage;
    @XmlAttribute(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;

    /**
     * Gets the value of the foutnummer property.
     * 
     */
    public int getFoutnummer() {
        return foutnummer;
    }

    /**
     * Sets the value of the foutnummer property.
     * 
     */
    public void setFoutnummer(int value) {
        this.foutnummer = value;
    }

    /**
     * Gets the value of the omschrijving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmschrijving() {
        return omschrijving;
    }

    /**
     * Sets the value of the omschrijving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmschrijving(String value) {
        this.omschrijving = value;
    }

    /**
     * Gets the value of the geefActueleVertrekTijdenRequestMessage property.
     * 
     * @return
     *     possible object is
     *     {@link GeefActueleVertrekTijdenRequestMessageType }
     *     
     */
    public GeefActueleVertrekTijdenRequestMessageType getGeefActueleVertrekTijdenRequestMessage() {
        return geefActueleVertrekTijdenRequestMessage;
    }

    /**
     * Sets the value of the geefActueleVertrekTijdenRequestMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeefActueleVertrekTijdenRequestMessageType }
     *     
     */
    public void setGeefActueleVertrekTijdenRequestMessage(GeefActueleVertrekTijdenRequestMessageType value) {
        this.geefActueleVertrekTijdenRequestMessage = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

}
