//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Het element InstapTip bevat instapinformatie.
 * 
 * <p>Java class for InstapTipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstapTipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstapTipTreinSoort" type="{urn:ndov:cdm:trein:reisinformatie:data:2}InstapTipTreinSoortType"/>
 *         &lt;element name="InstapTipUitstapStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *         &lt;element name="InstapTipTreinEindBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *         &lt;element name="InstapTipVertrekTijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="InstapTipVertrekSpoor" type="{urn:ndov:cdm:trein:reisinformatie:data:2}SpoorType" maxOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstapTipType", propOrder = {
    "instapTipTreinSoort",
    "instapTipUitstapStation",
    "instapTipTreinEindBestemming",
    "instapTipVertrekTijd",
    "instapTipVertrekSpoor"
})
public class InstapTipType {

    @XmlElement(name = "InstapTipTreinSoort", required = true)
    protected InstapTipTreinSoortType instapTipTreinSoort;
    @XmlElement(name = "InstapTipUitstapStation", required = true)
    protected StationType instapTipUitstapStation;
    @XmlElement(name = "InstapTipTreinEindBestemming", required = true)
    protected StationType instapTipTreinEindBestemming;
    @XmlElement(name = "InstapTipVertrekTijd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar instapTipVertrekTijd;
    @XmlElement(name = "InstapTipVertrekSpoor", required = true)
    protected List<SpoorType> instapTipVertrekSpoor;

    /**
     * Gets the value of the instapTipTreinSoort property.
     * 
     * @return
     *     possible object is
     *     {@link InstapTipTreinSoortType }
     *     
     */
    public InstapTipTreinSoortType getInstapTipTreinSoort() {
        return instapTipTreinSoort;
    }

    /**
     * Sets the value of the instapTipTreinSoort property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstapTipTreinSoortType }
     *     
     */
    public void setInstapTipTreinSoort(InstapTipTreinSoortType value) {
        this.instapTipTreinSoort = value;
    }

    /**
     * Gets the value of the instapTipUitstapStation property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getInstapTipUitstapStation() {
        return instapTipUitstapStation;
    }

    /**
     * Sets the value of the instapTipUitstapStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setInstapTipUitstapStation(StationType value) {
        this.instapTipUitstapStation = value;
    }

    /**
     * Gets the value of the instapTipTreinEindBestemming property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getInstapTipTreinEindBestemming() {
        return instapTipTreinEindBestemming;
    }

    /**
     * Sets the value of the instapTipTreinEindBestemming property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setInstapTipTreinEindBestemming(StationType value) {
        this.instapTipTreinEindBestemming = value;
    }

    /**
     * Gets the value of the instapTipVertrekTijd property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInstapTipVertrekTijd() {
        return instapTipVertrekTijd;
    }

    /**
     * Sets the value of the instapTipVertrekTijd property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setInstapTipVertrekTijd(XMLGregorianCalendar value) {
        this.instapTipVertrekTijd = value;
    }

    /**
     * Gets the value of the instapTipVertrekSpoor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instapTipVertrekSpoor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstapTipVertrekSpoor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.SpoorType }
     * 
     * 
     */
    public List<SpoorType> getInstapTipVertrekSpoor() {
        if (instapTipVertrekSpoor == null) {
            instapTipVertrekSpoor = new ArrayList<SpoorType>();
        }
        return this.instapTipVertrekSpoor;
    }

}
