//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ISO6391LanguageCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ISO6391LanguageCodeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="nl"/>
 *     &lt;enumeration value="en"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ISO6391LanguageCodeContentType")
@XmlEnum
public enum ISO6391LanguageCodeContentType {


    /**
     * Dutch; Flemish
     * 
     */
    @XmlEnumValue("nl")
    NL("nl"),

    /**
     * English
     * 
     */
    @XmlEnumValue("en")
    EN("en");
    private final String value;

    ISO6391LanguageCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ISO6391LanguageCodeContentType fromValue(String v) {
        for (ISO6391LanguageCodeContentType c: ISO6391LanguageCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
