//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Fysieke stukken materieel
 * 
 * <p>Java class for MaterieelDeelDVSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaterieelDeelDVSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaterieelSoort" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelSoortType"/>
 *         &lt;element name="MaterieelAanduiding" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelAanduidingType"/>
 *         &lt;element name="MaterieelLengte" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelLengteType"/>
 *         &lt;element name="MaterieelDeelVertrekPositie" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelDeelVertrekPositieType" minOccurs="0"/>
 *         &lt;element name="MaterieelDeelVolgordeVertrek" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelDeelVolgordeType" minOccurs="0"/>
 *         &lt;element name="MaterieelDeelEindBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationPlannedActueelType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="PresentatieMaterieelDeelEindBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;element name="SpoorVak" type="{urn:ndov:cdm:trein:reisinformatie:data:2}SpoorVakType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Wijziging" type="{urn:ndov:cdm:trein:reisinformatie:data:2}WijzigingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PresentatieWijziging" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaterieelDeelDVSType", propOrder = {
    "materieelSoort",
    "materieelAanduiding",
    "materieelLengte",
    "materieelDeelVertrekPositie",
    "materieelDeelVolgordeVertrek",
    "materieelDeelEindBestemming",
    "presentatieMaterieelDeelEindBestemming",
    "spoorVak",
    "wijziging",
    "presentatieWijziging"
})
public class MaterieelDeelDVSType {

    @XmlElement(name = "MaterieelSoort", required = true)
    protected String materieelSoort;
    @XmlElement(name = "MaterieelAanduiding", required = true)
    protected String materieelAanduiding;
    @XmlElement(name = "MaterieelLengte", required = true)
    protected BigInteger materieelLengte;
    @XmlElement(name = "MaterieelDeelVertrekPositie")
    protected BigInteger materieelDeelVertrekPositie;
    @XmlElement(name = "MaterieelDeelVolgordeVertrek")
    protected BigInteger materieelDeelVolgordeVertrek;
    @XmlElement(name = "MaterieelDeelEindBestemming", required = true)
    protected List<StationPlannedActueelType> materieelDeelEindBestemming;
    @XmlElement(name = "PresentatieMaterieelDeelEindBestemming")
    protected MeertaligeUitingenType presentatieMaterieelDeelEindBestemming;
    @XmlElement(name = "SpoorVak")
    protected List<String> spoorVak;
    @XmlElement(name = "Wijziging")
    protected List<WijzigingType> wijziging;
    @XmlElement(name = "PresentatieWijziging")
    protected MeertaligeUitingenType presentatieWijziging;

    /**
     * Gets the value of the materieelSoort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterieelSoort() {
        return materieelSoort;
    }

    /**
     * Sets the value of the materieelSoort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterieelSoort(String value) {
        this.materieelSoort = value;
    }

    /**
     * Gets the value of the materieelAanduiding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterieelAanduiding() {
        return materieelAanduiding;
    }

    /**
     * Sets the value of the materieelAanduiding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterieelAanduiding(String value) {
        this.materieelAanduiding = value;
    }

    /**
     * Gets the value of the materieelLengte property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMaterieelLengte() {
        return materieelLengte;
    }

    /**
     * Sets the value of the materieelLengte property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMaterieelLengte(BigInteger value) {
        this.materieelLengte = value;
    }

    /**
     * Gets the value of the materieelDeelVertrekPositie property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMaterieelDeelVertrekPositie() {
        return materieelDeelVertrekPositie;
    }

    /**
     * Sets the value of the materieelDeelVertrekPositie property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMaterieelDeelVertrekPositie(BigInteger value) {
        this.materieelDeelVertrekPositie = value;
    }

    /**
     * Gets the value of the materieelDeelVolgordeVertrek property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMaterieelDeelVolgordeVertrek() {
        return materieelDeelVolgordeVertrek;
    }

    /**
     * Sets the value of the materieelDeelVolgordeVertrek property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMaterieelDeelVolgordeVertrek(BigInteger value) {
        this.materieelDeelVolgordeVertrek = value;
    }

    /**
     * Gets the value of the materieelDeelEindBestemming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materieelDeelEindBestemming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterieelDeelEindBestemming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StationPlannedActueelType }
     * 
     * 
     */
    public List<StationPlannedActueelType> getMaterieelDeelEindBestemming() {
        if (materieelDeelEindBestemming == null) {
            materieelDeelEindBestemming = new ArrayList<StationPlannedActueelType>();
        }
        return this.materieelDeelEindBestemming;
    }

    /**
     * Gets the value of the presentatieMaterieelDeelEindBestemming property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieMaterieelDeelEindBestemming() {
        return presentatieMaterieelDeelEindBestemming;
    }

    /**
     * Sets the value of the presentatieMaterieelDeelEindBestemming property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieMaterieelDeelEindBestemming(MeertaligeUitingenType value) {
        this.presentatieMaterieelDeelEindBestemming = value;
    }

    /**
     * Gets the value of the spoorVak property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spoorVak property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpoorVak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpoorVak() {
        if (spoorVak == null) {
            spoorVak = new ArrayList<String>();
        }
        return this.spoorVak;
    }

    /**
     * Gets the value of the wijziging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wijziging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWijziging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.WijzigingType }
     * 
     * 
     */
    public List<WijzigingType> getWijziging() {
        if (wijziging == null) {
            wijziging = new ArrayList<WijzigingType>();
        }
        return this.wijziging;
    }

    /**
     * Gets the value of the presentatieWijziging property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieWijziging() {
        return presentatieWijziging;
    }

    /**
     * Sets the value of the presentatieWijziging property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieWijziging(MeertaligeUitingenType value) {
        this.presentatieWijziging = value;
    }

}
