//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ndov.cdm.trein.reisinformatie.data._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReisInformatieProductDVS_QNAME = new QName("urn:ndov:cdm:trein:reisinformatie:data:2", "ReisInformatieProductDVS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ndov.cdm.trein.reisinformatie.data._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReisInformatieProductDVSType }
     * 
     */
    public ReisInformatieProductDVSType createReisInformatieProductDVSType() {
        return new ReisInformatieProductDVSType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     * 
     */
    public StationType createStationType() {
        return new StationType();
    }

    /**
     * Create an instance of {@link VerstoringOnderwegType }
     * 
     */
    public VerstoringOnderwegType createVerstoringOnderwegType() {
        return new VerstoringOnderwegType();
    }

    /**
     * Create an instance of {@link AankomstOfVertrekTijdType }
     * 
     */
    public AankomstOfVertrekTijdType createAankomstOfVertrekTijdType() {
        return new AankomstOfVertrekTijdType();
    }

    /**
     * Create an instance of {@link DynamischeVertrekStaatType }
     * 
     */
    public DynamischeVertrekStaatType createDynamischeVertrekStaatType() {
        return new DynamischeVertrekStaatType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.TreinType }
     * 
     */
    public TreinType createTreinType() {
        return new TreinType();
    }

    /**
     * Create an instance of {@link MaterieelDeelDVSType }
     * 
     */
    public MaterieelDeelDVSType createMaterieelDeelDVSType() {
        return new MaterieelDeelDVSType();
    }

    /**
     * Create an instance of {@link RIPAdministratieType }
     * 
     */
    public RIPAdministratieType createRIPAdministratieType() {
        return new RIPAdministratieType();
    }

    /**
     * Create an instance of {@link OverstapTipType }
     * 
     */
    public OverstapTipType createOverstapTipType() {
        return new OverstapTipType();
    }

    /**
     * Create an instance of {@link MeertaligeUitingenType }
     * 
     */
    public MeertaligeUitingenType createMeertaligeUitingenType() {
        return new MeertaligeUitingenType();
    }

    /**
     * Create an instance of {@link VertrekInformatieType }
     * 
     */
    public VertrekInformatieType createVertrekInformatieType() {
        return new VertrekInformatieType();
    }

    /**
     * Create an instance of {@link StopStationsType }
     * 
     */
    public StopStationsType createStopStationsType() {
        return new StopStationsType();
    }

    /**
     * Create an instance of {@link TaalCodesType }
     * 
     */
    public TaalCodesType createTaalCodesType() {
        return new TaalCodesType();
    }

    /**
     * Create an instance of {@link EindBestemmingPlannedActueelType }
     * 
     */
    public EindBestemmingPlannedActueelType createEindBestemmingPlannedActueelType() {
        return new EindBestemmingPlannedActueelType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.ReisTipType }
     * 
     */
    public ReisTipType createReisTipType() {
        return new ReisTipType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.SpoorType }
     * 
     */
    public SpoorType createSpoorType() {
        return new SpoorType();
    }

    /**
     * Create an instance of {@link SpoorPlannedActueelType }
     * 
     */
    public SpoorPlannedActueelType createSpoorPlannedActueelType() {
        return new SpoorPlannedActueelType();
    }

    /**
     * Create an instance of {@link InstapTipTreinSoortType }
     * 
     */
    public InstapTipTreinSoortType createInstapTipTreinSoortType() {
        return new InstapTipTreinSoortType();
    }

    /**
     * Create an instance of {@link TreinSoortType }
     * 
     */
    public TreinSoortType createTreinSoortType() {
        return new TreinSoortType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.InstapTipType }
     * 
     */
    public InstapTipType createInstapTipType() {
        return new InstapTipType();
    }

    /**
     * Create an instance of {@link TreinVleugelType }
     * 
     */
    public TreinVleugelType createTreinVleugelType() {
        return new TreinVleugelType();
    }

    /**
     * Create an instance of {@link GeefActueleVertrekTijdenFaultMessageType }
     * 
     */
    public GeefActueleVertrekTijdenFaultMessageType createGeefActueleVertrekTijdenFaultMessageType() {
        return new GeefActueleVertrekTijdenFaultMessageType();
    }

    /**
     * Create an instance of {@link WijzigingType }
     * 
     */
    public WijzigingType createWijzigingType() {
        return new WijzigingType();
    }

    /**
     * Create an instance of {@link GeefActueleVertrekTijdenResponseMessageType }
     * 
     */
    public GeefActueleVertrekTijdenResponseMessageType createGeefActueleVertrekTijdenResponseMessageType() {
        return new GeefActueleVertrekTijdenResponseMessageType();
    }

    /**
     * Create an instance of {@link ActueleVertrekTijdenType }
     * 
     */
    public ActueleVertrekTijdenType createActueleVertrekTijdenType() {
        return new ActueleVertrekTijdenType();
    }

    /**
     * Create an instance of {@link StationPlannedActueelType }
     * 
     */
    public StationPlannedActueelType createStationPlannedActueelType() {
        return new StationPlannedActueelType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.UitingenType }
     * 
     */
    public UitingenType createUitingenType() {
        return new UitingenType();
    }

    /**
     * Create an instance of {@link VerkorteRouteType }
     * 
     */
    public VerkorteRouteType createVerkorteRouteType() {
        return new VerkorteRouteType();
    }

    /**
     * Create an instance of {@link ndov.cdm.trein.reisinformatie.data._2.UitingType }
     * 
     */
    public UitingType createUitingType() {
        return new UitingType();
    }

    /**
     * Create an instance of {@link GeefActueleVertrekTijdenRequestMessageType }
     * 
     */
    public GeefActueleVertrekTijdenRequestMessageType createGeefActueleVertrekTijdenRequestMessageType() {
        return new GeefActueleVertrekTijdenRequestMessageType();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ReisInformatieProductDVSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ndov:cdm:trein:reisinformatie:data:2", name = "ReisInformatieProductDVS")
    public JAXBElement<ReisInformatieProductDVSType> createReisInformatieProductDVS(ReisInformatieProductDVSType value) {
        return new JAXBElement<ReisInformatieProductDVSType>(_ReisInformatieProductDVS_QNAME, ReisInformatieProductDVSType.class, null, value);
    }

}
