//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Het element OverstapTip bevat overstapinformatie.
 * 
 * <p>Java class for OverstapTipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OverstapTipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OverstapTipBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *         &lt;element name="OverstapTipOverstapStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OverstapTipType", propOrder = {
    "overstapTipBestemming",
    "overstapTipOverstapStation"
})
public class OverstapTipType {

    @XmlElement(name = "OverstapTipBestemming", required = true)
    protected StationType overstapTipBestemming;
    @XmlElement(name = "OverstapTipOverstapStation", required = true)
    protected StationType overstapTipOverstapStation;

    /**
     * Gets the value of the overstapTipBestemming property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getOverstapTipBestemming() {
        return overstapTipBestemming;
    }

    /**
     * Sets the value of the overstapTipBestemming property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setOverstapTipBestemming(StationType value) {
        this.overstapTipBestemming = value;
    }

    /**
     * Gets the value of the overstapTipOverstapStation property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public StationType getOverstapTipOverstapStation() {
        return overstapTipOverstapStation;
    }

    /**
     * Sets the value of the overstapTipOverstapStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     *     
     */
    public void setOverstapTipOverstapStation(StationType value) {
        this.overstapTipOverstapStation = value;
    }

}
