//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Het element ReisTip bevat reistipinformatie. Geldt bij afwijkend stopgedrag ten opzichte van de de treinformule. Voorbeeld: "De stoptrein richting Amsterdam stopt niet in Bussum-Zuid".
 * 
 * <p>Java class for ReisTipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReisTipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReisTipStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="ReisTipCode" type="{urn:ndov:cdm:trein:reisinformatie:data:2}ReisTipCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReisTipType", propOrder = {
    "reisTipStation",
    "reisTipCode"
})
public class ReisTipType {

    @XmlElement(name = "ReisTipStation")
    protected List<StationType> reisTipStation;
    @XmlElement(name = "ReisTipCode", required = true)
    protected ReisTipCodeType reisTipCode;

    /**
     * Gets the value of the reisTipStation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reisTipStation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReisTipStation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StationType }
     * 
     * 
     */
    public List<StationType> getReisTipStation() {
        if (reisTipStation == null) {
            reisTipStation = new ArrayList<StationType>();
        }
        return this.reisTipStation;
    }

    /**
     * Gets the value of the reisTipCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReisTipCodeType }
     *     
     */
    public ReisTipCodeType getReisTipCode() {
        return reisTipCode;
    }

    /**
     * Sets the value of the reisTipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReisTipCodeType }
     *     
     */
    public void setReisTipCode(ReisTipCodeType value) {
        this.reisTipCode = value;
    }

}
