//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Het gedeelte van een perron dat aan de rails ligt, waar een trein stopt en reizigers kunnen in- en uitstappen. Het spoor datatype bevat een spoornummer en een optioneel spoorfase element.
 * 
 * <p>Java class for SpoorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpoorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpoorNummer" type="{urn:ndov:cdm:trein:reisinformatie:data:2}SpoorNummerType"/>
 *         &lt;element name="SpoorFase" type="{urn:ndov:cdm:trein:reisinformatie:data:2}SpoorFaseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpoorType", propOrder = {
    "spoorNummer",
    "spoorFase"
})
@XmlSeeAlso({
    SpoorPlannedActueelType.class
})
public class SpoorType {

    @XmlElement(name = "SpoorNummer")
    protected int spoorNummer;
    @XmlElement(name = "SpoorFase")
    protected String spoorFase;

    /**
     * Gets the value of the spoorNummer property.
     * 
     */
    public int getSpoorNummer() {
        return spoorNummer;
    }

    /**
     * Sets the value of the spoorNummer property.
     * 
     */
    public void setSpoorNummer(int value) {
        this.spoorNummer = value;
    }

    /**
     * Gets the value of the spoorFase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoorFase() {
        return spoorFase;
    }

    /**
     * Sets the value of the spoorFase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoorFase(String value) {
        this.spoorFase = value;
    }

}
