//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * Een TreinVleugel is een functionele opdeling van de trein, waarbij een andere route wordt gereden en een MaterieelDeel is hierbij het fysieke materieel, eventueel uniek gentificeerd door MaterieelNummer. Een MaterieelDeel, dat een deel van de route meerijdt en halverwege de rit achterblijft, behoort tot hetzelfde TreinVleugel als de MaterieelDelen, die de gehele route rijden.
 * 
 * <p>Java class for TreinVleugelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TreinVleugelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TreinVleugelVertrekSpoor" type="{urn:ndov:cdm:trein:reisinformatie:data:2}SpoorPlannedActueelType" maxOccurs="4" minOccurs="2"/>
 *         &lt;element name="PresentatieTreinVleugelVertrekSpoor" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;element name="TreinVleugelEindBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}EindBestemmingPlannedActueelType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="PresentatieTreinVleugelEindBestemming" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;element name="StopStations" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StopStationsType" maxOccurs="2"/>
 *         &lt;element name="Wijziging" type="{urn:ndov:cdm:trein:reisinformatie:data:2}WijzigingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PresentatieWijziging" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;element name="ReisTip" type="{urn:ndov:cdm:trein:reisinformatie:data:2}ReisTipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PresentatieReisTip" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MeertaligeUitingenType" minOccurs="0"/>
 *         &lt;element name="MaterieelDeelDVS" type="{urn:ndov:cdm:trein:reisinformatie:data:2}MaterieelDeelDVSType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TreinVleugelType", propOrder = {
    "treinVleugelVertrekSpoor",
    "presentatieTreinVleugelVertrekSpoor",
    "treinVleugelEindBestemming",
    "presentatieTreinVleugelEindBestemming",
    "stopStations",
    "wijziging",
    "presentatieWijziging",
    "reisTip",
    "presentatieReisTip",
    "materieelDeelDVS",
    "any"
})
public class TreinVleugelType {

    @XmlElement(name = "TreinVleugelVertrekSpoor", required = true)
    protected List<SpoorPlannedActueelType> treinVleugelVertrekSpoor;
    @XmlElement(name = "PresentatieTreinVleugelVertrekSpoor")
    protected MeertaligeUitingenType presentatieTreinVleugelVertrekSpoor;
    @XmlElement(name = "TreinVleugelEindBestemming", required = true)
    protected List<EindBestemmingPlannedActueelType> treinVleugelEindBestemming;
    @XmlElement(name = "PresentatieTreinVleugelEindBestemming")
    protected MeertaligeUitingenType presentatieTreinVleugelEindBestemming;
    @XmlElement(name = "StopStations", required = true)
    protected List<StopStationsType> stopStations;
    @XmlElement(name = "Wijziging")
    protected List<WijzigingType> wijziging;
    @XmlElement(name = "PresentatieWijziging")
    protected MeertaligeUitingenType presentatieWijziging;
    @XmlElement(name = "ReisTip")
    protected List<ReisTipType> reisTip;
    @XmlElement(name = "PresentatieReisTip")
    protected MeertaligeUitingenType presentatieReisTip;
    @XmlElement(name = "MaterieelDeelDVS")
    protected List<MaterieelDeelDVSType> materieelDeelDVS;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the treinVleugelVertrekSpoor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the treinVleugelVertrekSpoor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTreinVleugelVertrekSpoor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpoorPlannedActueelType }
     * 
     * 
     */
    public List<SpoorPlannedActueelType> getTreinVleugelVertrekSpoor() {
        if (treinVleugelVertrekSpoor == null) {
            treinVleugelVertrekSpoor = new ArrayList<SpoorPlannedActueelType>();
        }
        return this.treinVleugelVertrekSpoor;
    }

    /**
     * Gets the value of the presentatieTreinVleugelVertrekSpoor property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieTreinVleugelVertrekSpoor() {
        return presentatieTreinVleugelVertrekSpoor;
    }

    /**
     * Sets the value of the presentatieTreinVleugelVertrekSpoor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieTreinVleugelVertrekSpoor(MeertaligeUitingenType value) {
        this.presentatieTreinVleugelVertrekSpoor = value;
    }

    /**
     * Gets the value of the treinVleugelEindBestemming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the treinVleugelEindBestemming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTreinVleugelEindBestemming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EindBestemmingPlannedActueelType }
     * 
     * 
     */
    public List<EindBestemmingPlannedActueelType> getTreinVleugelEindBestemming() {
        if (treinVleugelEindBestemming == null) {
            treinVleugelEindBestemming = new ArrayList<EindBestemmingPlannedActueelType>();
        }
        return this.treinVleugelEindBestemming;
    }

    /**
     * Gets the value of the presentatieTreinVleugelEindBestemming property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieTreinVleugelEindBestemming() {
        return presentatieTreinVleugelEindBestemming;
    }

    /**
     * Sets the value of the presentatieTreinVleugelEindBestemming property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieTreinVleugelEindBestemming(MeertaligeUitingenType value) {
        this.presentatieTreinVleugelEindBestemming = value;
    }

    /**
     * Gets the value of the stopStations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopStations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopStations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.StopStationsType }
     * 
     * 
     */
    public List<StopStationsType> getStopStations() {
        if (stopStations == null) {
            stopStations = new ArrayList<StopStationsType>();
        }
        return this.stopStations;
    }

    /**
     * Gets the value of the wijziging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wijziging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWijziging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.WijzigingType }
     * 
     * 
     */
    public List<WijzigingType> getWijziging() {
        if (wijziging == null) {
            wijziging = new ArrayList<WijzigingType>();
        }
        return this.wijziging;
    }

    /**
     * Gets the value of the presentatieWijziging property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieWijziging() {
        return presentatieWijziging;
    }

    /**
     * Sets the value of the presentatieWijziging property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieWijziging(MeertaligeUitingenType value) {
        this.presentatieWijziging = value;
    }

    /**
     * Gets the value of the reisTip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reisTip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReisTip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.ReisTipType }
     * 
     * 
     */
    public List<ReisTipType> getReisTip() {
        if (reisTip == null) {
            reisTip = new ArrayList<ReisTipType>();
        }
        return this.reisTip;
    }

    /**
     * Gets the value of the presentatieReisTip property.
     * 
     * @return
     *     possible object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public MeertaligeUitingenType getPresentatieReisTip() {
        return presentatieReisTip;
    }

    /**
     * Sets the value of the presentatieReisTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeertaligeUitingenType }
     *     
     */
    public void setPresentatieReisTip(MeertaligeUitingenType value) {
        this.presentatieReisTip = value;
    }

    /**
     * Gets the value of the materieelDeelDVS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materieelDeelDVS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterieelDeelDVS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterieelDeelDVSType }
     * 
     * 
     */
    public List<MaterieelDeelDVSType> getMaterieelDeelDVS() {
        if (materieelDeelDVS == null) {
            materieelDeelDVS = new ArrayList<MaterieelDeelDVSType>();
        }
        return this.materieelDeelDVS;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3c.dom.Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
