//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UitingenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UitingenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Uiting" type="{urn:ndov:cdm:trein:reisinformatie:data:2}UitingType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Taal" type="{urn:ndov:cdm:trein:reisinformatie:data:2}TaalCodeEnumType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UitingenType", propOrder = {
    "uiting"
})
public class UitingenType {

    @XmlElement(name = "Uiting", required = true)
    protected List<UitingType> uiting;
    @XmlAttribute(name = "Taal")
    protected ISO6391LanguageCodeContentType taal;

    /**
     * Gets the value of the uiting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uiting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUiting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.UitingType }
     * 
     * 
     */
    public List<UitingType> getUiting() {
        if (uiting == null) {
            uiting = new ArrayList<UitingType>();
        }
        return this.uiting;
    }

    /**
     * Gets the value of the taal property.
     * 
     * @return
     *     possible object is
     *     {@link ISO6391LanguageCodeContentType }
     *     
     */
    public ISO6391LanguageCodeContentType getTaal() {
        return taal;
    }

    /**
     * Sets the value of the taal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO6391LanguageCodeContentType }
     *     
     */
    public void setTaal(ISO6391LanguageCodeContentType value) {
        this.taal = value;
    }

}
