//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Beschrijft de verstoring op de route. Alleen aanwezig indien er een verstoring is.
 * 				
 * 
 * <p>Java class for VerstoringOnderwegType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerstoringOnderwegType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VerstoringDossierNr" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="VerstoringSoort" type="{urn:ndov:cdm:trein:reisinformatie:data:2}VerstoringType"/>
 *         &lt;element name="RitStationInVerstoordBvk" type="{urn:ndov:cdm:trein:reisinformatie:data:2}indicatie" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerstoringOnderwegType", propOrder = {
    "verstoringDossierNr",
    "verstoringSoort",
    "ritStationInVerstoordBvk"
})
public class VerstoringOnderwegType {

    @XmlElement(name = "VerstoringDossierNr", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger verstoringDossierNr;
    @XmlElement(name = "VerstoringSoort", required = true)
    protected VerstoringType verstoringSoort;
    @XmlElement(name = "RitStationInVerstoordBvk")
    protected Indicatie ritStationInVerstoordBvk;

    /**
     * Gets the value of the verstoringDossierNr property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getVerstoringDossierNr() {
        return verstoringDossierNr;
    }

    /**
     * Sets the value of the verstoringDossierNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setVerstoringDossierNr(BigInteger value) {
        this.verstoringDossierNr = value;
    }

    /**
     * Gets the value of the verstoringSoort property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.VerstoringType }
     *     
     */
    public VerstoringType getVerstoringSoort() {
        return verstoringSoort;
    }

    /**
     * Sets the value of the verstoringSoort property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.VerstoringType }
     *     
     */
    public void setVerstoringSoort(VerstoringType value) {
        this.verstoringSoort = value;
    }

    /**
     * Gets the value of the ritStationInVerstoordBvk property.
     * 
     * @return
     *     possible object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.Indicatie }
     *     
     */
    public Indicatie getRitStationInVerstoordBvk() {
        return ritStationInVerstoordBvk;
    }

    /**
     * Sets the value of the ritStationInVerstoordBvk property.
     * 
     * @param value
     *     allowed object is
     *     {@link ndov.cdm.trein.reisinformatie.data._2.Indicatie }
     *     
     */
    public void setRitStationInVerstoordBvk(Indicatie value) {
        this.ritStationInVerstoordBvk = value;
    }

}
