//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.data._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dit element bevat informatie over een wijziging van een trein ten opzichte van de dienstregeling richting eindbestemming van de rit.
 * 
 * <p>Java class for WijzigingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WijzigingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WijzigingType" type="{urn:ndov:cdm:trein:reisinformatie:data:2}WijzigingTypeType"/>
 *         &lt;element name="WijzigingOorzaakKort" type="{urn:ndov:cdm:trein:reisinformatie:data:2}WijzigingOorzaakKortType" minOccurs="0"/>
 *         &lt;element name="WijzigingOorzaakLang" type="{urn:ndov:cdm:trein:reisinformatie:data:2}WijzigingOorzaakLangType" minOccurs="0"/>
 *         &lt;element name="WijzigingStation" type="{urn:ndov:cdm:trein:reisinformatie:data:2}StationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TVVOmschrijving" type="{urn:ndov:cdm:trein:reisinformatie:data:2}TVVOmschrijvingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WijzigingType", propOrder = {
    "wijzigingType",
    "wijzigingOorzaakKort",
    "wijzigingOorzaakLang",
    "wijzigingStation",
    "tvvOmschrijving"
})
public class WijzigingType {

    @XmlElement(name = "WijzigingType", required = true)
    protected String wijzigingType;
    @XmlElement(name = "WijzigingOorzaakKort")
    protected String wijzigingOorzaakKort;
    @XmlElement(name = "WijzigingOorzaakLang")
    protected String wijzigingOorzaakLang;
    @XmlElement(name = "WijzigingStation")
    protected List<StationType> wijzigingStation;
    @XmlElement(name = "TVVOmschrijving")
    protected String tvvOmschrijving;

    /**
     * Gets the value of the wijzigingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWijzigingType() {
        return wijzigingType;
    }

    /**
     * Sets the value of the wijzigingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWijzigingType(String value) {
        this.wijzigingType = value;
    }

    /**
     * Gets the value of the wijzigingOorzaakKort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWijzigingOorzaakKort() {
        return wijzigingOorzaakKort;
    }

    /**
     * Sets the value of the wijzigingOorzaakKort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWijzigingOorzaakKort(String value) {
        this.wijzigingOorzaakKort = value;
    }

    /**
     * Gets the value of the wijzigingOorzaakLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWijzigingOorzaakLang() {
        return wijzigingOorzaakLang;
    }

    /**
     * Sets the value of the wijzigingOorzaakLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWijzigingOorzaakLang(String value) {
        this.wijzigingOorzaakLang = value;
    }

    /**
     * Gets the value of the wijzigingStation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wijzigingStation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWijzigingStation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ndov.cdm.trein.reisinformatie.data._2.StationType }
     * 
     * 
     */
    public List<StationType> getWijzigingStation() {
        if (wijzigingStation == null) {
            wijzigingStation = new ArrayList<StationType>();
        }
        return this.wijzigingStation;
    }

    /**
     * Gets the value of the tvvOmschrijving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTVVOmschrijving() {
        return tvvOmschrijving;
    }

    /**
     * Sets the value of the tvvOmschrijving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTVVOmschrijving(String value) {
        this.tvvOmschrijving = value;
    }

}
