//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ndov:cdm:trein:reisinformatie:messages:3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ndov.cdm.trein.reisinformatie.messages._3;
