//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 09:16:58 PM CEST 
//


package ndov.cdm.trein.reisinformatie.messages._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ndov:cdm:trein:reisinformatie:messages:3}ReisInformatieProductDVSResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reisInformatieProductDVSResponse"
})
@XmlRootElement(name = "PutReisInformatieBoodschapOut")
public class PutReisInformatieBoodschapOut {

    @XmlElement(name = "ReisInformatieProductDVSResponse", required = true)
    protected ReisInformatieProductDVSResponse reisInformatieProductDVSResponse;

    /**
     * Gets the value of the reisInformatieProductDVSResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ReisInformatieProductDVSResponse }
     *     
     */
    public ReisInformatieProductDVSResponse getReisInformatieProductDVSResponse() {
        return reisInformatieProductDVSResponse;
    }

    /**
     * Sets the value of the reisInformatieProductDVSResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReisInformatieProductDVSResponse }
     *     
     */
    public void setReisInformatieProductDVSResponse(ReisInformatieProductDVSResponse value) {
        this.reisInformatieProductDVSResponse = value;
    }

}
